# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=admin
spring.datasource.password=admin123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080